"""
reports/report_generator.py

Phase 5: turns an investigated InvestigationCase into a standalone incident
report -- the artifact an analyst actually forwards or files, as opposed
to the CLI output made for reading in a terminal.

Two formats:
  - markdown (stdlib only, always available)
  - html (needs Jinja2 -- see requirements.txt)

Both are pure presentation over the same InvestigationCase tree Phase 1-3
already built; this module makes zero investigation decisions of its own,
same discipline as the orchestrator.
"""

import os
from datetime import datetime, timezone

from core.models import InvestigationCase


def _severity_badge(severity: str) -> str:
    colors = {"low": "#2e7d32", "medium": "#f9a825", "high": "#e65100", "critical": "#c62828"}
    return colors.get(severity, "#616161")


def to_markdown(case: InvestigationCase) -> str:
    lines = []
    lines.append(f"# PhishMind Incident Report -- {case.case_id}")
    lines.append("")
    lines.append(f"**Source file:** `{case.source_file}`  ")
    lines.append(f"**Analyzed at:** {case.analyzed_at}  ")
    lines.append(f"**Subject:** {case.subject or '(none)'}  ")
    lines.append("")

    ta = case.threat_assessment
    if ta:
        lines.append(f"## Verdict: {ta.verdict.upper()}")
        lines.append(f"- **Severity:** {ta.severity}")
        lines.append(f"- **Confidence:** {ta.confidence}")
        lines.append(f"- **Analyst review recommended:** {ta.analyst_review_recommended}")
        if ta.possible_attack_objective:
            lines.append(f"- **Possible objective:** {ta.possible_attack_objective}")
        lines.append("")
        lines.append("### Reasons")
        for r in ta.reasons:
            lines.append(f"- {r}")
        if ta.mitre_techniques:
            lines.append("")
            lines.append("### MITRE ATT&CK")
            for t in ta.mitre_techniques:
                lines.append(f"- `{t.technique_id}` -- {t.technique_name} (justified by: {', '.join(t.justified_by) or 'n/a'})")
        if ta.missing_evidence:
            lines.append("")
            lines.append("### Missing evidence / limitations")
            for m in ta.missing_evidence:
                lines.append(f"- {m}")

    ra = case.recommended_action
    if ra:
        lines.append("")
        lines.append("### Recommended action")
        lines.append(f"- **Action:** {ra.action} (requires human approval: {ra.requires_human_approval})")
        lines.append(f"- **Rationale:** {ra.rationale}")

    lines.append("")
    lines.append("## Sender analysis")
    s = case.sender
    lines.append(f"- From: {s.from_display_name} <{s.from_address}>")
    lines.append(f"- Reply-To mismatch: {s.reply_to_mismatch}")
    lines.append(f"- Return-Path mismatch: {s.return_path_mismatch}")
    lines.append(f"- Display-name spoof suspected: {s.display_name_spoof_suspected}")

    a = case.authentication
    lines.append("")
    lines.append("## Authentication (as reported by receiving server)")
    if a.header_present:
        lines.append(f"- SPF: {a.spf} | DKIM: {a.dkim} | DMARC: {a.dmarc}")
    else:
        lines.append("- No Authentication-Results header present.")

    e = case.evidence
    lines.append("")
    lines.append("## Evidence")
    lines.append(f"- URLs ({len(e.urls)}): " + (", ".join(e.urls) if e.urls else "none"))
    lines.append(f"- Domains ({len(e.domains)}): " + (", ".join(e.domains) if e.domains else "none"))
    lines.append(f"- Public IPs ({len(e.ip_addresses)}): " + (", ".join(e.ip_addresses) if e.ip_addresses else "none"))
    lines.append(f"- Attachments ({len(e.attachments)}): " + (", ".join(f"{att.filename} ({att.sha256[:12]}...)" for att in e.attachments) if e.attachments else "none"))

    if case.agent_findings:
        lines.append("")
        lines.append("## Agent findings")
        for f in case.agent_findings:
            lines.append(f"### {f.agent_name} (confidence={f.confidence}, severity={f.severity})")
            lines.append(f"{f.finding}")
            lines.append("")

    if case.enrichment_results:
        lines.append("## Threat-intel enrichment")
        for r in case.enrichment_results:
            if r.available:
                lines.append(f"- {r.source} / {r.indicator}: malicious_votes={r.malicious_votes}, reputation_score={r.reputation_score}")
            else:
                lines.append(f"- {r.source} / {r.indicator}: unavailable ({r.reason})")

    lines.append("")
    lines.append(f"*Generated by PhishMind on {datetime.now(timezone.utc).isoformat()}. "
                  f"All recommended actions require human analyst approval before execution.*")

    return "\n".join(lines)


HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>PhishMind Report -- {{ case.case_id }}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 860px; margin: 40px auto; color: #1a1a1a; line-height: 1.5; }
  h1 { font-size: 22px; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 4px; color: white; font-weight: 600; font-size: 13px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  td, th { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 14px; }
  th { background: #f5f5f5; }
  .section { margin-top: 28px; }
  code { background: #f0f0f0; padding: 1px 5px; border-radius: 3px; }
  ul { margin: 6px 0; }
  .footer { margin-top: 40px; font-size: 12px; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head>
<body>
  <h1>PhishMind Incident Report</h1>
  <p><strong>Case:</strong> {{ case.case_id }} &nbsp;|&nbsp; <strong>Source:</strong> <code>{{ case.source_file }}</code></p>
  <p><strong>Subject:</strong> {{ case.subject or "(none)" }} &nbsp;|&nbsp; <strong>Analyzed:</strong> {{ case.analyzed_at }}</p>

  {% if ta %}
  <div class="section">
    <h2>Verdict: <span class="badge" style="background:{{ badge_color }}">{{ ta.verdict.upper() }}</span></h2>
    <p>Severity: <strong>{{ ta.severity }}</strong> &nbsp;|&nbsp; Confidence: <strong>{{ ta.confidence }}</strong>
       &nbsp;|&nbsp; Analyst review recommended: <strong>{{ ta.analyst_review_recommended }}</strong></p>
    {% if ta.possible_attack_objective %}<p>Possible objective: {{ ta.possible_attack_objective }}</p>{% endif %}
    <h3>Reasons</h3>
    <ul>{% for r in ta.reasons %}<li>{{ r }}</li>{% endfor %}</ul>
    {% if ta.mitre_techniques %}
    <h3>MITRE ATT&amp;CK</h3>
    <ul>{% for t in ta.mitre_techniques %}<li><code>{{ t.technique_id }}</code> -- {{ t.technique_name }}</li>{% endfor %}</ul>
    {% endif %}
    {% if ta.missing_evidence %}
    <h3>Missing evidence / limitations</h3>
    <ul>{% for m in ta.missing_evidence %}<li>{{ m }}</li>{% endfor %}</ul>
    {% endif %}
  </div>
  {% endif %}

  {% if ra %}
  <div class="section">
    <h3>Recommended action</h3>
    <p><strong>{{ ra.action }}</strong> (requires human approval: {{ ra.requires_human_approval }})<br>{{ ra.rationale }}</p>
  </div>
  {% endif %}

  <div class="section">
    <h3>Sender analysis</h3>
    <table>
      <tr><th>From</th><td>{{ case.sender.from_display_name }} &lt;{{ case.sender.from_address }}&gt;</td></tr>
      <tr><th>Reply-To mismatch</th><td>{{ case.sender.reply_to_mismatch }}</td></tr>
      <tr><th>Return-Path mismatch</th><td>{{ case.sender.return_path_mismatch }}</td></tr>
      <tr><th>Display-name spoof suspected</th><td>{{ case.sender.display_name_spoof_suspected }}</td></tr>
    </table>
  </div>

  <div class="section">
    <h3>Authentication</h3>
    {% if case.authentication.header_present %}
    <table>
      <tr><th>SPF</th><td>{{ case.authentication.spf }}</td></tr>
      <tr><th>DKIM</th><td>{{ case.authentication.dkim }}</td></tr>
      <tr><th>DMARC</th><td>{{ case.authentication.dmarc }}</td></tr>
    </table>
    {% else %}<p>No Authentication-Results header present.</p>{% endif %}
  </div>

  <div class="section">
    <h3>Evidence</h3>
    <p><strong>URLs ({{ case.evidence.urls|length }}):</strong> {{ case.evidence.urls|join(", ") or "none" }}</p>
    <p><strong>Domains ({{ case.evidence.domains|length }}):</strong> {{ case.evidence.domains|join(", ") or "none" }}</p>
    <p><strong>Public IPs ({{ case.evidence.ip_addresses|length }}):</strong> {{ case.evidence.ip_addresses|join(", ") or "none" }}</p>
  </div>

  {% if case.agent_findings %}
  <div class="section">
    <h3>Agent findings</h3>
    {% for f in case.agent_findings %}
    <p><strong>{{ f.agent_name }}</strong> (confidence={{ f.confidence }}, severity={{ f.severity }})<br>{{ f.finding }}</p>
    {% endfor %}
  </div>
  {% endif %}

  <div class="footer">Generated by PhishMind. All recommended actions require human analyst approval before execution.</div>
</body>
</html>
"""


def to_html(case: InvestigationCase) -> str:
    try:
        from jinja2 import Template
    except ImportError as exc:
        raise RuntimeError(
            "HTML report generation requires jinja2 (pip install jinja2 --break-system-packages). "
            "Use --report md for a dependency-free alternative."
        ) from exc

    template = Template(HTML_TEMPLATE)
    ta = case.threat_assessment
    badge_color = _severity_badge(ta.severity) if ta else "#616161"
    return template.render(case=case, ta=ta, ra=case.recommended_action, badge_color=badge_color)


def write_report(case: InvestigationCase, fmt: str, out_dir: str = "reports") -> str:
    os.makedirs(out_dir, exist_ok=True)
    ext = "html" if fmt == "html" else "md"
    path = os.path.join(out_dir, f"{case.case_id}.{ext}")
    content = to_html(case) if fmt == "html" else to_markdown(case)
    with open(path, "w") as f:
        f.write(content)
    return path

